CREATE OR REPLACE PROCEDURE AJUSTA_DESCONTOS_FATO AS
BEGIN
    UPDATE FATO_VENDAS
    SET VAL_DESCONTO = 0
    WHERE VAL_DESCONTO < 1;

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Descontos ajustados com sucesso.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro na procedure AJUSTA_DESCONTOS_FATO: ' || SQLERRM);
        ROLLBACK;
END AJUSTA_DESCONTOS_FATO;
