CREATE OR REPLACE PROCEDURE TRATA_DADOS_DIMENSOES AS
BEGIN
    UPDATE DIM_CLIENTE
    SET NOME_CLIENTE = LIMPA_CARACTERES_ESPECIAIS(NOME_CLIENTE);

    UPDATE DIM_LOCALIZACAO
    SET CIDADE = LIMPA_CARACTERES_ESPECIAIS(CIDADE);

    UPDATE DIM_PRODUTO
    SET NOME_PRODUTO = LIMPA_CARACTERES_ESPECIAIS(NOME_PRODUTO),
        CATEGORIA = LIMPA_CARACTERES_ESPECIAIS(CATEGORIA);

    UPDATE DIM_VENDEDOR
    SET NOME_VENDEDOR = LIMPA_CARACTERES_ESPECIAIS(NOME_VENDEDOR);

    COMMIT;
    DBMS_OUTPUT.PUT_LINE('Dados tratados com sucesso.');
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('Erro ao tratar dados das dimensões: ' || SQLERRM);
        ROLLBACK;
END TRATA_DADOS_DIMENSOES;
